# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    providers:
        #in_memory:
            #memory: 
                #users:
                    #ryan:
                        #password: ryanpass
                        #roles: 'ROLE_USER'
                    #admin:
                        #password: kitten
                        #roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle:User
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #http_basic: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
            logout:
                path: /logout
                target: /
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/activate, roles: ROLE_CASHIER }
        - { path: ^/viewapplications, roles: ROLE_ADMIN }
        - { path: ^/fullInfo, roles: ROLE_ADMIN }
        - { path: ^/continue, roles: ROLE_STUDENT_APP }
        - { path: ^/printSlip, roles: ROLE_STUDENT_APP }
        - { path: ^/printSlip2, roles: ROLE_STUDENT_APP }
        - { path: ^/edit, roles: ROLE_STUDENT_APP }
        - { path: ^/printSlip3, roles: ROLE_STUDENT_APP }
        